### ISSUE TITLE
Config Diff

### ISSUE THREAD

**Issue by hasechris** [linux-surface/kernel-configs-old#2]
Hi,

please correct me if I've misunderstood something. In this repo are the complete config files, right?

I currently have the requirement to merge many kernel config files. Could you therefore only specify the surface-specific changes in a separate file?

Best regards from Germany
hasechris

**Comment by qzed** [comment]
Something like this has been on my TODO-list for a while now. I think diffs won't quite work, but a list of options and a bit of scripting should do the trick. I'm not sure when I get to that, however, as it's going to be a bit of work to figure out all the dependencies and include them. In the mean-time, here's a list without the dependencies:

```
# IPTS Touchscreen
CONFIG_INTEL_IPTS=m
CONFIG_INTEL_IPTS_SURFACE=m

# Surface SAM
CONFIG_SURFACE_SAM=m
CONFIG_SURFACE_SAM_SSH=m
CONFIG_SURFACE_SAM_SSH_DEBUG_DEVICE=y
CONFIG_SURFACE_SAM_SAN=m
CONFIG_SURFACE_SAM_VHF=m
CONFIG_SURFACE_SAM_DTX=m
CONFIG_SURFACE_SAM_HPS=m
CONFIG_SURFACE_SAM_SID=m
CONFIG_SURFACE_SAM_SID_GPELID=m
CONFIG_SURFACE_SAM_SID_PERFMODE=m
CONFIG_SURFACE_SAM_SID_VHF=m
CONFIG_SURFACE_SAM_SID_POWER=m

CONFIG_SURFACE_3_POWER_OPREGION=m
```

Also note that those are only the ones added by the kernel patches. There's other stuff (e.g. `CONFIG_SURFACE_3_BUTTON=m`) which is already provided upstream.

**Comment by hasechris** [comment]
That would work really well :) I'm new to the kernel stuff but a list like your example would work.

Here an example of aufs patches in manjaro: https://gitlab.manjaro.org/packages/core/linux53/blob/master/config.aufs

> There's other stuff (e.g. CONFIG_SURFACE_3_BUTTON=m) which is already provided upstream.

What means this? Are the Options already set the right way in the mainline source files? Or do i have to set the config options in my "to be generated config file" anyways?

**Comment by qzed** [comment]
> Here an example of aufs patches in manjaro: https://gitlab.manjaro.org/packages/core/linux53/blob/master/config.aufs
> Lists like this can be used really easy with scripting or like PKGBUILD from archlinux.

Thanks for that example, I'll keep that in mind when I get to creating the list.



> > There's other stuff (e.g. CONFIG_SURFACE_3_BUTTON=m) which is already provided upstream.
> 
> What means this? Are the Options already set the right way in the mainline source files? Or do i have to set the config options in my "to be generated config file" anyways?

What I meant by that is that the option is provided by the upstream kernel source code. It depends on the base-configuration you choose, but I think normal distributions intended for desktop use (Manjaro, Arch, Debian, Ubuntu, ...) _should_ already set that to `m` (or maybe `y`, but I can't guarantee you that of course). That's actually the thing that will probably take most of the time: Figuring out which options the upstream kernel provides that should be enabled for the Surface devices so that everything works with basically every base config. Getting the options from the patches is fairly easy as those are only a couple of files.

**Comment by hasechris** [comment]
Hm ok..

i made a config diff between Manjaro and your config:

```
-BOOTSPLASH y
-DRM_I915_FORCE_PROBE "*"
-DRM_I915_SPIN_REQUEST 5
-DRM_I915_USERFAULT_AUTOSUSPEND 250
-TICK_CPU_ACCOUNTING y
-USER_NS_UNPRIVILEGED y
 DEFAULT_HOSTNAME "manjaro" -> "archlinux"
 GOOGLE_SMI n -> m
 INIT_ON_ALLOC_DEFAULT_ON y -> n
 LOCALVERSION "-MANJARO" -> ""
 MODVERSIONS y -> n
 NO_HZ_FULL n -> y
 NO_HZ_IDLE y -> n
 RCU_FANOUT 64 -> 32
 RCU_NOCB_CPU n -> y
 RMI4_F54 n -> y
 SECURITY_DMESG_RESTRICT y -> n
 SLUB_CPU_PARTIAL y -> n
 SND_SOC_FSL_AUDMIX n -> m
 SND_SOC_FSL_MICFIL n -> m
 SND_SOC_INTEL_SKYLAKE_HDAUDIO_CODEC n -> y
 SND_SOC_SOF_TOPLEVEL n -> y
 VIRT_CPU_ACCOUNTING_GEN n -> y
 X86_INTEL_TSX_MODE_AUTO y -> n
 X86_INTEL_TSX_MODE_OFF n -> y
 X86_X32 y -> n
+CONTEXT_TRACKING y
+CONTEXT_TRACKING_FORCE n
+INTEL_IPTS m
+INTEL_IPTS_SURFACE m
+SND_SOC_HDAC_HDA m
+SND_SOC_INTEL_SKL_HDA_DSP_GENERIC_MACH m
+SND_SOC_INTEL_SOF_RT5682_MACH m
+SND_SOC_SOF m
+SND_SOC_SOF_ACPI m
+SND_SOC_SOF_APOLLOLAKE m
+SND_SOC_SOF_APOLLOLAKE_SUPPORT y
+SND_SOC_SOF_BAYTRAIL m
+SND_SOC_SOF_BAYTRAIL_SUPPORT y
+SND_SOC_SOF_BROADWELL m
+SND_SOC_SOF_BROADWELL_SUPPORT y
+SND_SOC_SOF_CANNONLAKE m
+SND_SOC_SOF_CANNONLAKE_SUPPORT y
+SND_SOC_SOF_COFFEELAKE m
+SND_SOC_SOF_COFFEELAKE_SUPPORT y
+SND_SOC_SOF_COMETLAKE_H m
+SND_SOC_SOF_COMETLAKE_H_SUPPORT y
+SND_SOC_SOF_COMETLAKE_LP m
+SND_SOC_SOF_COMETLAKE_LP_SUPPORT y
+SND_SOC_SOF_DEBUG n
+SND_SOC_SOF_GEMINILAKE m
+SND_SOC_SOF_GEMINILAKE_SUPPORT y
+SND_SOC_SOF_HDA m
+SND_SOC_SOF_HDA_ALWAYS_ENABLE_DMI_L1 n
+SND_SOC_SOF_HDA_AUDIO_CODEC y
+SND_SOC_SOF_HDA_COMMON m
+SND_SOC_SOF_HDA_LINK y
+SND_SOC_SOF_HDA_LINK_BASELINE m
+SND_SOC_SOF_ICELAKE m
+SND_SOC_SOF_ICELAKE_SUPPORT y
+SND_SOC_SOF_INTEL_ACPI m
+SND_SOC_SOF_INTEL_ATOM_HIFI_EP m
+SND_SOC_SOF_INTEL_COMMON m
+SND_SOC_SOF_INTEL_HIFI_EP_IPC m
+SND_SOC_SOF_INTEL_PCI m
+SND_SOC_SOF_INTEL_TOPLEVEL y
+SND_SOC_SOF_MERRIFIELD m
+SND_SOC_SOF_MERRIFIELD_SUPPORT y
+SND_SOC_SOF_NOCODEC_SUPPORT n
+SND_SOC_SOF_OPTIONS m
+SND_SOC_SOF_PCI m
+SND_SOC_SOF_PROBE_WORK_QUEUE y
+SND_SOC_SOF_STRICT_ABI_CHECKS n
+SND_SOC_SOF_XTENSA m
+SURFACE_3_POWER_OPREGION m
+SURFACE_BOOK2_DGPU_HPS m
+SURFACE_SAM m
+SURFACE_SAM_DTX m
+SURFACE_SAM_SAN m
+SURFACE_SAM_SID m
+SURFACE_SAM_SID_GPELID m
+SURFACE_SAM_SID_PERFMODE m
+SURFACE_SAM_SID_POWER m
+SURFACE_SAM_SID_VHF m
+SURFACE_SAM_SSH m
+SURFACE_SAM_SSH_DEBUG_DEVICE y
+SURFACE_SAM_VHF m
+VIRT_CPU_ACCOUNTING y
```

There is not really much difference between this two. I suspect these options to be the surface specific ones:

```
+INTEL_IPTS m
+INTEL_IPTS_SURFACE m
+SURFACE_3_POWER_OPREGION m
+SURFACE_BOOK2_DGPU_HPS m
+SURFACE_SAM m
+SURFACE_SAM_DTX m
+SURFACE_SAM_SAN m
+SURFACE_SAM_SID m
+SURFACE_SAM_SID_GPELID m
+SURFACE_SAM_SID_PERFMODE m
+SURFACE_SAM_SID_POWER m
+SURFACE_SAM_SID_VHF m
+SURFACE_SAM_SSH m
+SURFACE_SAM_SSH_DEBUG_DEVICE y
+SURFACE_SAM_VHF m
```

I will try a kernel build with this options. Should i post a pull reuest if successfull?

Greetings

**Comment by qzed** [comment]
I think a PR is a bit early at this point, but feel free to post your list if it has changed.

**Comment by qzed** [comment]
I've completely restructured the approach we take with configs. New repo is at https://github.com/linux-surface/kernel-configs providing a minimal list of options (e.g. https://github.com/linux-surface/kernel-configs/blob/master/5.4/surface.config) for each kernel version. In addition, some pre-generated and tested configs are provided (e.g. https://github.com/linux-surface/kernel-configs/tree/master/5.4/generated) to help figure out configuration issues.

Let me know over there if you have any issues. I will archive this repo now.
